export const SET_ORDERS = 'SET_ORDERS'
export const SET_SELECTED_ORDER = 'SET_SELECTED_ORDER'

export const SET_EDITED_ENTRY = 'SET_EDITED_ENTRY'
export const SET_EDITED_ENTRY_VALUE = 'SET_EDITED_ENTRY_VALUE'
