version: '2'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
  selenium-server:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    volumes:
      - ./errorShots:/home/ubuntu/locks-and-keys/errorShots
  selenium-server-host:
    image: selenium/standalone-chrome
    network_mode: "host"
